# Generated by Django 4.0.4 on 2022-05-30 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=150, verbose_name='Dni')),
                ('fecha_nac', models.DateField(verbose_name='Fecha_nacimiento')),
                ('direccion', models.CharField(max_length=150)),
                ('sexo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now=True, verbose_name='Fecha_venta')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Iva')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total')),
                ('id_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagen/%Y/%m/%d')),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Pvp')),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Subtotal')),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.venta')),
            ],
            options={
                'verbose_name': 'Detalle_Venta',
                'verbose_name_plural': 'Detalles_Ventas',
                'db_table': 'detalle_venta',
                'ordering': ['id'],
            },
        ),
    ]
